on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.rdslv.sk
        username: rdslv.sk
        password: ${{ secrets.password }}
        protocol: ftps
        port: 222 # todo replace with your web hosts ftps port
        server-dir: /public_html/
        timeout: 120000
